version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      groups:
        name: "all"  # Group name for all updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      groups:
        python-packages:
          patterns:
            - "*"
